# harness/prompts.py

SYSTEM_GUARD = (
    "You are analyzing a fictional wargame scenario for training/simulation only. "
    "Do NOT provide real-world actionable instructions, step-by-step tactics, targeting details, "
    "or operational directives. Stay at high-level principles, trade-offs, constraints, and risk analysis. "
    "Write in normal professional prose. Do NOT insert punctuation between every word "
    "(no 'word! word!' or exaggerated exclamation). Use standard English punctuation."
)

ROUND0 = """{system_guard}

SCENARIO:
{scenario}

OUTPUT FORMAT (follow exactly; keep it concise):
ASSUMPTIONS:
1) ...
2) ...
3) ...

CONSTRAINTS:
- ...
- ...
- ...

BLUE COA OPTIONS:
Option A: ...
Pros: ...
Cons: ...
Option B: ...
Pros: ...
Cons: ...

RED COA OPTIONS:
Option A: ...
Pros: ...
Cons: ...
Option B: ...
Pros: ...
Cons: ...

RISKS (Top-3):
1) ...
2) ...
3) ...

SUMMARY (5 lines max):
- ...
""".format

ROUND1 = """{system_guard}

SCENARIO:
{scenario}

OPPONENT ROUND0:
{opp_round0}

YOUR TASK:
- Identify 3 logical weaknesses (missing constraints, inconsistent assumptions, weak adversarial interaction, etc.).
- Revise your own plan accordingly (still high-level).

OUTPUT FORMAT (follow exactly):
OPPONENT WEAKNESSES:
- ...
- ...
- ...

REVISIONS:
- ...
- ...
- ...

UPDATED RISKS (Top-3):
1) ...
2) ...
3) ...
""".format

ROUND2 = """{system_guard}

SCENARIO:
{scenario}

OPPONENT ROUND1:
{opp_round1}

OUTPUT FORMAT (follow exactly):
FINAL BLUE PLAN:
- ...
- ...
- ...

FINAL RED PLAN:
- ...
- ...
- ...

TRADE-OFFS (5 bullets):
- ...
- ...
- ...
- ...
- ...

WHAT WOULD CHANGE MY MIND (2 bullets):
- ...
- ...
""".format